### ISSUE TITLE
Clarify privacy and security implications

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#10]
Provide specific requirements for the following, or remove entirely:

_Each specification should contain a section detailing any known security or privacy implications for implementers, Web authors, and end users._

Also, "web authors" is too narrow.

**Comment by tmichel07** [comment]
This statement comes from the W3C Charter Template.
https://w3c.github.io/charter-drafts/charter-template.html

Therefore, I am not sure I can remove it

So let's discuss it during our call

Thierry

**Comment by nigelmegitt** [comment]
I'm happy to leave this as is.

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]. Proposed alternate wording is:

> Each specification should contain a section discussing security and privacy.

**Comment by tmichel07** [comment]
Previous statement Replaced with 

Each specification should contain a section discussing security and privacy.

**Comment by nigelmegitt** [comment]
Done as per the WG discussion; closing.
