### ISSUE TITLE
Clarify accessibility section

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#12]
Remove, or provide specific requirements for the following:

_Each specification should contain a section on accessibility that describes the benefits and impacts, including ways specification features can be used to address them, and recommendations for maximising accessibility in implementations._

This clause is redundant with the scope (_should address the Media Accessibility User Requirements_) and vague.

**Comment by tmichel07** [comment]
This statement comes from the W3C Charter Template.
https://w3c.github.io/charter-drafts/charter-template.html

Therefore, I am not sure I can remove it

So let's discuss it during our call

Thierry

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today] Group uncertain of the motivation behind the clause, majority view is to remove for now, but will accept reinstatement with explanation of the intent by W3M.

**Comment by tmichel07** [comment]
Paragrah removed.

**Comment by nigelmegitt** [comment]
Closing as done as per WG decision.
