### ISSUE TITLE
Clarify testing requirements

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#13]
Remove, or provide specific requirements for:

_To promote interoperability, all changes made to specifications should have tests._

This also should be moved to a section other than "deliverables" since it impacts the process of creating deliverables, and not the deliverable itself.

**Comment by tmichel07** [comment]
This statement comes from the W3C Charter Template.
https://w3c.github.io/charter-drafts/charter-template.html

Therefore, I am not sure I can remove it

So let's discuss it during our call

Thierry

**Comment by palemieux** [comment]
@tmichel07 Can you move the statement to a section called "Development of Deliverables"?

**Comment by nigelmegitt** [comment]
@palemieux 's suggestion would work for me. I'd like to keep the statement in somewhere, as a "should".

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]

1. Add to a new subsection "Development of deliverables"
2. Reword to: "All substantive changes to specifications should have associated tests."

**Comment by tmichel07** [comment]
Removed,
"To promote interoperability, all changes made to specifications should have tests."
Added section 2.3 "Development of deliverables"
All substantive changes to specifications should have associated tests.

**Comment by nigelmegitt** [comment]
Closing as done as agreed by WG.
