### ISSUE TITLE
TTML2 expected completion

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#14]
The expected publication of TTML2 should be October 2018 since it is required for the publication of IMSC 1.1, also slated for October 2018.

**Comment by tmichel07** [comment]
Are you saying that TTML2 should be a REC in october 2018. Sounds tight 
to me.

So let's discuss this timing during our call

Thierry

**Comment by palemieux** [comment]
@tmichel07 Yes, October is the objective since there is industry interest in completing IMSC 1.1 by October, and IMSC 1.1 depends on TTML2.

**Comment by tmichel07** [comment]
OK, so the Group needs to commit to this deadline.
We have top publish a second CR, have implementations, implementation 
report, mover to PR  and REC.

I hope it is doable ...

**Comment by nigelmegitt** [comment]
We have discussed this before and already agreed to it. Actually my recollection was November not October, but it's close enough.
