### ISSUE TITLE
Missing deliverable: TTML1 3ED

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#16]
The deliverables section is missing TTML1 3ED, also due in October 2018

See https://lists.w3.org/Archives/Public/public-tt/2018Mar/0019.html

**Comment by tmichel07** [comment]
I had listed
Updates to Timed Text Markup Language 1 (TTML1) (Second Edition), W3C 
Recommendation

therefore we could have a 3rd, 4th, etc. if needed ...

**Comment by palemieux** [comment]
Ok... but TTML1 3ED is an in-process deliverable with a target publication date, so I would think the charter should mention it, not unlike it mentions IMSC 1.0.1 explicitly.

**Comment by tmichel07** [comment]
It will be difficucult to say 

Updates to Timed Text Markup Language 1 (TTML1) (Third Edition), W3C
as it does exist yet.

**Comment by palemieux** [comment]
@tmichel07 The target publication date is this week to TTML1 3ED.

**Comment by tmichel07** [comment]
I dought that will be possible.
The transition request is currently in the hands of Nigel for review.
Then needs to be sent to the Director (currently ion China with low 
availability).
Maybe next week we can get transition approuval.
Then need to prepare spec, announcement, and request publication.

thierry

**Comment by palemieux** [comment]
Pretty unfortunate to hear re: delay. In any case, the charter needs to include TTML1 3ED as an explicit deliverable.
