### ISSUE TITLE
Remove participation requirement

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#17]
Where does the requirement for "5 active participants" come from? Remove unless this is a process requirement, or explain the objective.

**Comment by tmichel07** [comment]
This statement comes from the W3C Charter Template.
https://w3c.github.io/charter-drafts/charter-template.html

Therefore, I am not sure I can remove it

So let's discuss it during our call

Thierry

**Comment by palemieux** [comment]
@tmichel07 In preparation for our call, can you check where that requirement came from, and what is the objective?

**Comment by tmichel07** [comment]
I said previouslly that it comes from the W3C charter Template. I will ask W3M if it is mandatory.

**Comment by palemieux** [comment]
@tmichel07 A template is just a template, and items should be removable unless required by the documented process.

>  I will ask W3M if it is mandatory.

... and why it is mandatory.

**Comment by tmichel07** [comment]
Well here is what PlH told me:

You cannot remove the statement but you need to adjust it to what you believe is the reality. For example, in reality, if we have a success with less than 6, say adjust the number as needed. After that, let's have the Director/AC make the judgment call on whether it's worth having a working group and/or the amount of team resources for that group.

**Comment by palemieux** [comment]
@tmichel07 The criteria for success should be industry adoption and on-time deliverables, not an arbitrary number of "active" participants, right? In particular, a participant might not be active in the WG, but nevertheless an adopter. Futhermore, some participants represent organizations that consist of multiple independent adopters.

**Comment by tmichel07** [comment]
We could argue ... , but it is up to W3M. I forwarded PlH's argument above, about this statement added  in the new charter template.

**Comment by palemieux** [comment]
> but it is up to W3M.

I do not see a clause in the process that allows W3M to set requirements beyond those specified in the process. In fact, the latter states: _To allow rapid progress, Working Groups are intended to be small (typically fewer than 15 people)_

To be sure, I am trying to simplify the charter, and be efficient with resources.

**Comment by tmichel07** [comment]
Sorry I have no authority here. We can ask PlH to explain W3M position 
about charters, if you think it is necessary.

**Comment by palemieux** [comment]
> We can ask PlH to explain W3M position about charters, if you think it is necessary.

@tmichel07 I definitely think it is necessary since I do not think the TTWG should commit to requirements without understanding them.

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today] My understanding is that this is an expectation, and not a requirement, and counting current active members, we meet that expectation now.
