### ISSUE TITLE
Add text for liaisons with other SDO's

### ISSUE THREAD

**Issue by andreastai** [w3c/charter-timed-text#18]
A lot of standard organisations depend on the work of the Timed Text Working Group. This needs to be reflected in the charter.

I propose to add the following as topic 5 to the list under `1. Scope`: 

`Liaise with external standard organisations that are dependent on TTML and IMSC recommendations (see 3.2).`

**Comment by nigelmegitt** [comment]
There was enough wording for this in the previous (current) charter and I think this is already in 3.2, so not sure if we need to add anything extra. Liaisons are a normal part of WG operation I think.

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]

Add new bullet at end of Scope section:

> 6. Liaise with other organisations including but not limited to those listed in §3.2.

**Comment by tmichel07** [comment]
Bullet added.

**Comment by nigelmegitt** [comment]
Closing as done as agreed by WG.
