### ISSUE TITLE
Add requirements analysis for immersive media

### ISSUE THREAD

**Issue by andreastai** [w3c/charter-timed-text#19]
As discussed at the [f2f at TPAC 2017](https://www.w3.org/2017/11/09-tt-minutes.html#item44
) and the [f2f in Cupertino 2018](https://www.w3.org/2018/01/10-tt-minutes.html#item49) there is currently no solution for captions in 360 Degree Content, Augemented Reality (AR) and Virtual Reality (VR). 

There should be a topic added to the list in Section 1:

`Investigate caption format requirements for 360 Degree, AR and VR video content`

**Comment by nigelmegitt** [comment]
Not sure if this is a WG thing, or if interested people should be setting up a CG for this (or if M&E IG should set up a task force), and if there is something concrete, bring that to the WG with a Charter addition. Would like W3 steer please @plehegar @tmichel07 .

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]

Add a bullet to the scope section:

> 7. Investigate caption format requirements for 360 Degree, AR and VR video content.

**Comment by tmichel07** [comment]
Bullet added in scope.

**Comment by nigelmegitt** [comment]
Closing as done as agreed by WG.
