### ISSUE TITLE
set end date

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#2]
presumably to 31st March 2020 or 2021

**Comment by tmichel07** [comment]
done

**Comment by nigelmegitt** [comment]
[taken up in TTWG today]

Add possible reqmt for future versions of IMSC and TTML.

Set end date to begin + 2 years.

**Comment by tmichel07** [comment]
Done
changed to start date 01 may 2018 end date 3à april 2020

**Comment by nigelmegitt** [comment]
It says "Avril" instead of "April". I presume we need the English spelling for consistency.

**Comment by nigelmegitt** [comment]
I've fixed the month, also added a todo to set it to start date + 2 years. Closing.
