### ISSUE TITLE
Interaction with  WICG

### ISSUE THREAD

**Issue by andreastai** [w3c/charter-timed-text#20]
We should interact with the Web Incubator Community Group (WICG) to incubate solutions for new requirements (such as captions for VR/AR).

This needs to be reflected in the charter.

This was also discussed at the [TPAC 2017 f2f](https://www.w3.org/2017/11/09-tt-minutes.html#item44)

**Comment by nigelmegitt** [comment]
I don't believe there's anything to add to the Charter for this - if any CG (WICG or another) proposes something that needs to go on a Rec track then the WG Charter can be reviewed and amended to include it. Is there anything specific you have in mind @tairt ?

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]. Add a statement to section 3 Coordination:

> The Working Group will consider inputs provided by Community Groups including WICG for example to add new features.

**Comment by tmichel07** [comment]
Added Statement in section 3.1

**Comment by nigelmegitt** [comment]
Closing as done as agreed by WG - actually I had expected this in §3 header not §3.1 but I think this is fine, since that's the W3C groups section.
