### ISSUE TITLE
Implement WebVTT resolution

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#21]
As recorded at https://www.w3.org/2016/09/19-tt-minutes.html#resolution01, we made a resolution at TPAC in Lisbon in 2016 regarding WebVTT and the Charter. Is there any reason not to implement that resolution now?

**Comment by dwsinger** [comment]
I want to be sure that before we embark on the CR and a new charter, we have the resources to pull through.

**Comment by silviapfeiffer** [comment]
As the TTWG seems to allocate preferential time to moving TTML and its derivatives forward, and it seems impossible to find a new editor for webvtt, I find myself wondering what value this group is associating with webvtt. I provide my spare time freely to addressing the extra requests this group keeps coming up with before moving webvtt forward, something the rest of the W3C has long since agreed to. The perfect is the enemy of the good enough. We could move to CR today of this group was willing.

**Comment by dwsinger** [comment]
> On Mar 26, 2018, at 10:59 , Silvia Pfeiffer <notifications@github.com> wrote:
> 
> As the TTWG seems to allocate preferential time to moving TTML and its derivatives forward, and it seems impossible to find a new editor for webvtt, I find myself wondering what value this group is associating with webvtt. I provide my spare time freely to addressing the extra requests this group keeps coming up with before moving webvtt forward, something the rest of the W3C has long since agreed to. The perfect is the enemy of the good enough. We could move to CR today of this group was willing.
> 

Agreed, we could, and could have. Would we exit? We’d need to have
* implementations brought up to date to match all these detailed changes
* the test suite run manually (how?) by the non-browser implementations
* and all that documented

I wonder about the road sign at junctions “do not enter the box unless your exit is clear”


David Singer
Manager, Software Standards, Apple Inc.

**Comment by silviapfeiffer** [comment]
So your argument for not moving to CR is that we don't have everything implemented yet? You've got it upside down: browsers like Edge won't implement until it's in CR!

**Comment by dwsinger** [comment]
> On Mar 26, 2018, at 11:13 , Silvia Pfeiffer <notifications@github.com> wrote:
> 
> So your argument for not moving to CR is that we don't have everything implemented yet? You've got it upside down: browsers like Edge won't implement until it's in CR!

OK, I will complete the CR transition (with you) in the next few days, and we’ll satisfy the Lisbon accords, and thus be in the charter for the next period.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by dwsinger** [comment]
Transition request draft [4] had only minor changes requested by Nigel, so those changes have been made, and it's before the WG for a resolution.

**Comment by nigelmegitt** [comment]
WebVTT CR has been published within the extended Charter, so this is moot. Closing.
