### ISSUE TITLE
Require maintenance of registries

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#22]
We should list in the Charter a requirement to maintain registries and list the current registries. I'm thinking of the TTML `@ttm:role` and the TTML Profiles registries specifically.

**Comment by nigelmegitt** [comment]
[Taken up by TTWG today]

Add registries to "other non-normative documents".

**Comment by tmichel07** [comment]
Added statement.

**Comment by nigelmegitt** [comment]
The media type and profile registry was already separately listed but the URL was broken. I fixed the URL and removed it from the new bullet, and added a link to the `ttm:role` attribute registry, in 997fe58. I think this is now fixed, closing.
