### ISSUE TITLE
Revert Decision Policy?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#27]
The current draft allows the Chairs to determine the review period, being somewhere between a week and 10 working days. The current Charter specifies it is always 10 days. Should we revert to the [current active decision policy](https://www.w3.org/2016/05/timed-text-charter.html#decisions)  which uses the text:

> Any Decision taken is to be considered provisional for 10 working days after it has been recorded by the Chair and sent to the working group's mailing list.

instead of the draft text:

> A call for consensus (CfC) will be issued for all resolutions (for example, via email and/or web-based survey), with a response period from one week to 10 working days, depending on the chair's evaluation of the group consensus on the issue. 

Additionally, I think we _should_ change the language to include resolutions recorded in emailed group meeting minutes to be considered as CfC by default, for the avoidance of doubt.

**Comment by nigelmegitt** [comment]
To clarify, I would prefer to revert and not have the discretion as the Chair.

**Comment by palemieux** [comment]
Why was the change made in the first place?

**Comment by nigelmegitt** [comment]
Good question @palemieux - I don't really know but I think the current wording came from the draft charter template and wasn't updated by @tmichel07 when he applied the changes to align it with the current TTWG Charter. To compound the problem, I didn't notice it and think about the impact until too late.

**Comment by nigelmegitt** [comment]
**AC Reps** I'd really appreciate it if you could request that the change to revert this to a fixed 10 day period is applied when you vote on the Charter in the AC survey.

@dwsinger are you happy to revert to a fixed 10 days period also? If both proposed Chairs can agree this then that should make it easy for others also to request/accept the change in the Charter.

**Comment by dwsinger** [comment]
Yes, fixed 10 (or "at least 10") is better.

**Comment by nigelmegitt** [comment]
Thanks @dwsinger if making this reversion can be requested as part of Apple's AC review of the Charter that would be super helpful.
