### ISSUE TITLE
Support modularisation for TTML

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#35]
During the recent face to face meeting, when discussing [support for live contribution](https://github.com/w3c/tt-reqs/issues/3#issuecomment-459298286) the TTWG agreed to pursue a model for an update of TTML, TTML3, in which there will be a modularisation framework, and agreed to add this to the next Charter in such as way as to allow the TTWG to determine the appropriate structure of Rec track documents to work on during its work without requiring a new Charter revision each time a new Rec track document is begun.

Amend the 2019 Charter draft to permit this.

**Comment by nigelmegitt** [comment]
@skynavga in https://github.com/w3c/ttml3/pull/30 you posit a "Module Registry" - that needs to be added to the Charter.

Question: do you intend the registry itself to be 1) Part of the TTML3 specification (i.e. a module) or 2) a WG Note or 3) a separate Rec track Technical Report?

**Comment by skynavga** [comment]
Firstly, I do not agree with your premise of referring to TTML3 and its modules as a single specification. CSS is a broken model as far as I'm concerned in this regard, and should not be copied. For me a specification (in this context) is a single document.

**Comment by nigelmegitt** [comment]
OK, I don't mind framing it a different way; that was my starting point.

It would be useful to know what about the CSS model is broken @skynavga so we can avoid creating the same issues.

**Comment by nigelmegitt** [comment]
One point in favour of the "single specification" model is that it enables us to factor in or out parts of TTML3 without affecting the overall scope. For the sake of argument, say we decide that the audio module is to be moved to a separate document: one thing it would be good to claim is that the functionality remains _part of_ TTML3, and that we are not removing the features.

I'd like to be able to retain that characteristic in whatever other formulation we arrive at.

**Comment by skynavga** [comment]
I think that moving the (now internal) Audio Module into a separate document, and change the registry to say external rather than internal, could (and would) still make it defined in the scope of TTML3. No (external) module will be in scope for TTML2 or TTML1. Each external module will normatively refer to TTML3 (or TTML4, etc.), and we will mark in the registry which version of TTML the module was first introduced under.

The only utility in referring to the group of specifications that include {TTML3, Module1, Module2, ...} as a "single specification" (via an abuse of notation I might add) seems to be related to marketing some point in the charter, and that seems a pretty poor reason to do so. If you want to use "TTML3 specification group" or "TTML3 specification collection" in the charter, that would be fine, and we wouldn't be having this discussion.

**Comment by nigelmegitt** [comment]
> we wouldn't be having this discussion.

@skynavga We're having this discussion because I put forward a proposal and you said you didn't agree and that the model is broken, but I don't think you've explained what is broken about it yet. In my view the definition of "specification" is sufficiently loose to allow for it to include one or multiple documents, and we can define it. I'd like to know what "broken" thing we're avoiding so I can understand why we are making any change to the proposal.

**Comment by skynavga** [comment]
Here is the broken thing we are trying to avoid: https://www.w3.org/TR/CSS/.

**Comment by skynavga** [comment]
And, by the way, even that document does not refer to the group of base and module documents as a single specification, e.g.,

>As of 2018, Cascading Style Sheets (CSS) is defined by the following specifications.

**Comment by nigelmegitt** [comment]
> Here is the broken thing we are trying to avoid: https://www.w3.org/TR/CSS/.

I don't follow how the need for a snapshot is a consequence of the way the CSS WG Charter is defined. In my view it is more a function of the fact that real world usage has preceded advancement to Rec of several of the CSS modules.

I take the point that the snapshot text itself does not match what the CSS WG Charter says though, in that the use of the term "spec" or "specification" seems to differ.

An alternative proposal would be useful at this point @skynavga .

**Comment by skynavga** [comment]
My proposal would be not to attempt to characterize the collection of base plus modules as a single specification (it is not). If you want to refer to it as a "specification collection" or as "specifications", that works for me. The main reason is that, by and large, we mean by "specification" a single document, and not a collection of related documents on different publishing timelines and at different levels of maturity. See the intro of the "CSS über alles" document I referred to for their rationale.

**Comment by nigelmegitt** [comment]
@skynavga Whether a specification is a single document or a collection of documents is within our power to define in this context. I agree it is easier in natural language to say that each document is a specification in its own right. 

How about defining that TTML3 is a "language" defined by a collection of "specifications"?

**Comment by skynavga** [comment]
No, that doesn't work either. TTML3 (along with TTML2, TTML1) are collectively referred to as the Timed Text Markup Language, which is singular (as a language per se). What is wrong with using the phrase "specification collection" in the charter? It is singular and accurate.

**Comment by nigelmegitt** [comment]
It might work, but to my ears anyway, "specification collection" sounds clunky.
