### ISSUE TITLE
Clarify mapping to HTML/CSS

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#4]
Change

_Will provide a mapping with HTML5/CSS3, including describing TTML intermediate synchronic document as HTML5 document fragment, and understanding how the presentation syntax and semantics relate to CSS3._

to

_facilitate mapping to HTML5/CSS3_

**Comment by tmichel07** [comment]
Updated

**Comment by nigelmegitt** [comment]
[taken up in TTWG meeting today]

Add HTML5/CSS3 mapping as an optional deliverable, and also leave in the existing place in TTML2 scope.

Remove the "non-normative" qualification to 2.2 Other deliverables.

**Comment by tmichel07** [comment]
Done: 
Add HTML5/CSS3 mapping as an optional deliverable
Remove the "non-normative" qualification to 2.2 Other deliverables.

**Comment by nigelmegitt** [comment]
I think this is good to close - @palemieux you raised the issue: do you agree?
