### ISSUE TITLE
Horizontal reviews

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-timed-text#55]
The recent thread on the CSS charter concluding with a new agreement around horizontal review timeline/requirement. This propose to align the Timed Text charter with the CSS one. Specifically,
replace
[[
For all specifications, this Working Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the TAG. Invitation for review must be issued during each major standards-track document transition, including FPWD and at least 3 months before first entering CR, and should be issued when major changes occur in a specification.
]]
with
[[
For all specifications, this Working Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the TAG. Invitation for review must be issued during each major standards-track document transition, including FPWD. The Working Group is encouraged to engage collaboratively with the horizontal review groups throughout development of each specification. The Working Group is advised to seek a review at least 3 months before CR and is encouraged to proactively notify the horizontal review groups when major changes occur in a specification following a review.
]]

@nigelmegitt @palemieux

**Comment by nigelmegitt** [comment]
this has lost the word "first" and I think it's still important in this updated wording, which is otherwise a good improvement. I'd like it to say "seek a review at least 3 months before first entering CR" still.

**Comment by plehegar** [comment]
For reference: https://github.com/w3c/charter-drafts/issues/219
