### ISSUE TITLE
Nits

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-timed-text#56]
Editorial: in the Scope section, the word "of" is used too many times:
"...two independent implementations of each of feature defined..." 

"in online media". So, one can't use these formats in a CD-ROM? Not sure what 'online' adds here.

**Comment by plehegar** [comment]
given the current debate around the Accessibility Guidelines charter, I'd rather not touch the word "online"....

**Comment by nigelmegitt** [comment]
@plehegar are you saying you really need to remove "online" or that we should not make a change at this time?

**Comment by plehegar** [comment]
I suggest not making the change

**Comment by nigelmegitt** [comment]
Agreed yesterday in the [TTWG call](https://www.w3.org/2019/11/21-tt-minutes.html#x03) to remove the word "online".
