### ISSUE TITLE
Implementation experience requirement in success criteria

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#66]
Section 3 ("Success Criteria") should merely require [adequate implementation experience](https://www.w3.org/2020/Process-20200915/#implementation-experience) as defined in W3 process, instead of the narrower requirement that _each normative specification is expected to have at least two independent implementations of every feature defined in the specification_.

Rationale:

- the charter should avoid duplicating/interpreting/superseding the W3 process
- _two independent implementations_ is only one means of demonstrating implementation experience. In some cases, it might be equally appropriate, if not preferable, to have a single common open-source implementation accompanied by a large number of samples from multiple parties.

**Comment by skynavga** [comment]
I agree with the above; furthermore, we should adjust our implementation report and SoDT on our current documents undergoing REC track processing to reflect this point.

**Comment by gkatsev** [comment]
It does seem like this came from the main charter template, https://w3c.github.io/charter-drafts/charter-template.html#success-criteria. Though, there the text says
> each normative specification is expected to have

as opposed to
> each Recommendation-track Technical Report SHOULD have

But, I'm not sure if one is looser or stricter than the other.

While I agree that two separate implementations aren't necessarily the only way to showcase adequate implementation experience, I do worry if the reference implementation is mostly implemented by the spec authors that it will be adequate.

**Comment by palemieux** [comment]
> I do worry if the reference implementation is mostly implemented by the spec authors that it will be adequate.

This can be mitigated if documents/stimuli/tests written by others are provided.

More importantly, why should the charter go beyond what is required by process.

**Comment by gkatsev** [comment]
Yup, overall, I'm in agreement that it doesn't seem necessary to include this phrase as the Process document already covers it.

**Comment by himorin** [comment]
I think it's clearly defined in the Process text

https://www.w3.org/2020/Process-20200915/#implementation-experience
> While no exhaustive list of requirements is provided here, when assessing that there is adequate implementation experience the Director will consider (though not be limited to):
> are there independent interoperable implementations of the current specification? 
> are there implementations created by people other than the authors of the specification?

**Comment by nigelmegitt** [comment]
@himorin the trouble is that our experience has been (and others have also raised this) that Process text is very far from clear. It was slightly cleaned up in Process revisions over the past couple of years, but the main problem that is not resolved is that the requirements for progression are not documented, just the sorts of things the Director will consider.

I think this means that if we state in the Charter things like:
* Within the requirements that the Process sets out, we will consider normative features as ready to progress if we have demonstrated _implementability_ primarily.
* When considering suitability to progress, the WG will consider it appropriate to cite at least 2 factors of verification, which may come from any of:
   * Presentation Implementation
   * Content
   * Validating Implementation
* For example, we may request progression on the basis of a single open source implementation plus content from an independent source.

then we have a) not duplicated Process text and b) explained to the AC what our working basis is. Then if we request advancement past CR for a feature, taking this approach, but there is only 1 _implementation_ , we can cite the AC's approval of the Charter.

**Comment by himorin** [comment]
For here, I cannot say or state anything further than the text in the Process document, even it is far from clear...
So, how about to draft a text to include points listed in your comment, and to update our draft, and to bring it to [the charter review process](https://github.com/w3c/strategy/issues/new?assignees=&labels=Evaluation%3A+untriaged&template=04-Chartering.md&title=)?

**Comment by nigelmegitt** [comment]
I don't think that updating the charter template is a gate to updating our own charter: however if we get to agreement on wording that we want to use, then we can take it back to update the charter template.

**Comment by himorin** [comment]
@nigelmegitt how about to close this, per PR #67 merged?

**Comment by nigelmegitt** [comment]
I agree @himorin we have resolved this issue via #67. Closing.
