### ISSUE TITLE
Remove item 1.4

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#7]
Remove

_Finalyse a semantic mapping between TTML and WebVTT in order to facilitate browser implementation and market adoption._

since there are no volunteers.

**Comment by tmichel07** [comment]
removed

**Comment by nigelmegitt** [comment]
Is it true there are no volunteers? @tairt did volunteer to do some of this, but wanted to wait until WebVTT was more stable. I imagine others might step in again to help with that.

**Comment by andreastai** [comment]
It's fine to keep it under section 2.2. Here it says:

>Other non-normative documents may be updated such as:
> ...
> * the Mapping between TTML and WebVTT, a Working Group Note;

This is in line what we disucssed at the f2f meeting at TPAC 2017.
