### ISSUE TITLE
Fix history section

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-timed-text#77]
History section should explain:

- What's happening with "Dubbing and Audio description Profiles of TTML2". (The latter was in the previous charter, so it's not clear why you're calling it out here.)
- The name shift, of TTML3 to TTML2 "Second Edition"
- The other new deliverable (HRM)

**Comment by skynavga** [comment]
Not in scope.

**Comment by skynavga** [comment]
Reopening, as I (initially) read this comment as applying to TTML related change documents. I'll defer to the chair for follow on.
