### ISSUE TITLE
Remove item 1.5

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#8]
Remove

_Maintain a simple constrained profile for delivery of closed captions for video content ("TTML Simple Delivery Profile for Closed Captions (US)") for TTML._

unless there is explicit interest in doing so.

SDP-US has essentially been replaced by IMSC.

**Comment by tmichel07** [comment]
removed

**Comment by nigelmegitt** [comment]
Sorry, I think we need to keep this, otherwise it prevents us from making any maintenance update in case we think it is needed. I believe no work would be required, but I think it's a general point that the TTWG charter should permit the group to maintain any of its previous output in case some need is identified.

**Comment by palemieux** [comment]
@nigelmegitt I am not opposed to keeping it as long as it does not compel the group to spend any resource on it.

**Comment by nigelmegitt** [comment]
Thanks @palemieux , from previous iterations of the Charter, my understanding is to think of the Charter document as something that both enables and also sets limits on what the WG can do. If an activity is not in the Charter, that effectively prevents work on it, especially when it comes to anything like a Recommendation. Of course SDP-US is merely a Note, so it's not a big deal in this particular case.

**Comment by palemieux** [comment]
@nigelmegitt I think it is ok to keep it under "Other non-normative documents may be updated such as", but not as a main deliverable.

[EDITED]

**Comment by andreastai** [comment]
+1 Agree to seperate main deliverables from documents that are maintained and updated if necessary.

**Comment by tmichel07** [comment]
That is currently the case.

**Comment by nigelmegitt** [comment]
Works for me.
