### ISSUE TITLE
Address Apple's FO

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-timed-text#85]
@gkatsev @hober @dwsinger and @nigelmegitt met to discuss Apple's FO and potential resolutions to it. We determined that changing the success criteria factors of verification 2nd bullet from "content implementation" to "content-producing implementation" would allow Apple to remove their objection.

One of the clarifications in understanding that I had during that discussion was that in the case of a private implementation, say one created and used by a broadcaster or content provider, an assertion that the implementation exists plus a significant corpus of content from that implementation, would be enough to satisfy the criterion that a "content-producing implementation" exists.

Another is that a content-producing implementation that is asserted to meet any validation requirements in the specification in question does not necessarily have to be a validating implementation: for example, the implementer could arrange for tighter authoring constraints to be in place than are strictly needed, with the intention that the output cannot be invalid, without running a validator on the implementation's output.

On this basis I will propose a pull request that implements this proposal.

**Comment by palemieux** [comment]
> On this basis I will propose a pull request that implements this proposal.

+1
